
export const rows = [
    {
        id: 1,
        name: "adham",
        email: "@fwfSnow.com",
        age: 14,
        phone: "+201099627615",
        access: "admin",
    },
    {
        id: 2,
        name: "adham",
        email: "Lannister",
        age: 14,
        phone: "+201099627615",
        access: "admin",
    },
    {
        id: 3,
        name: "adham",
        email: "Lannister",
        age: 14,
        phone: "+201099627615",
        access: "admin",
    },
    {
        id: 4,
        name: "adham",
        email: "Stark",
        age: 14,
        phone: "+201099627615",
        access: "manager",
    },
    {
        id: 5,
        name: "adham",
        email: "Targaryen",
        age: 14,
        phone: "+201099627615",
        access: "manager",
    },
    {
        id: 6,
        name: "adham",
        email: "Melisandre",
        age: 14,
        phone: "+201099627615",
        access: "user",
    },
    {
        id: 7,
        name: "adham",
        email: "Clifford",
        age: 14,
        phone: "+201099627615",
        access: "user",
    },
    {
        id: 8,
        name: "adham",
        email: "Frances",
        age: 14,
        phone: "+201099627615",
        access: "user",
    },
    {
        id: 9,
        name: "adham",
        email: "@Roxie",
        age: 14,
        phone: "+201099627615",
        access: "user",
    },
];
